version: 0.2

env:
  shell: bash
  secrets-manager:
    DOCKERHUB_USERNAME: "arn:aws:secretsmanager:ap-southeast-1:485644516808:secret:docker_credentials-e0xKlv:DOCKERHUB_USERNAME"
    DOCKERHUB_PASSWORD: "arn:aws:secretsmanager:ap-southeast-1:485644516808:secret:docker_credentials-e0xKlv:DOCKERHUB_PASSWORD"

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Logging in to Docker registry..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - echo "Building Spring Boot application..."
      - cd m3project/
      - ./mvnw test -q
      - ./mvnw clean package -q
      - echo "Building the Docker image..."
      - docker build -t benchan79/mod4-project-docker:latest .
      - docker tag benchan79/mod4-project-docker:latest benchan79/mod4-project-docker:latest
      - echo "Pushing Docker image to registry..."
      - docker push benchan79/mod4-project-docker:latest
  post_build:
    commands:
      - echo "Project deployed."

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - "/root/.m2/**/*"
